server:
  port: 8888
  tomcat:
    connect-timeout: 2s
    keepalive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  applications:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ivypas/cloud-native-spring-in-action-config-repo.git
          default-lable: main  # equals branch in github
